### ISSUE TITLE
Question about the process of collecting RGB-D and pose data in real-world

### ISSUE THREAD

**Issue by AbbeGo** [hovsg/HOV-SG#1]
If I understand correctly, the HOV-SG method requires collecting RGB-D and pose information of scenes before real-world application. However, your paper does not specifically explain the process of data collection. I would like to know whether the locomotion of the robotic dog in the scene depends on manual operation or is implemented through algorithms?

**Comment by Tom-Huang** [comment]
As is introduced in the paper, we first manually drive the robot around to collect RGB-D sequences. To get more precise odometry information, we also collected the 3D LiDAR sequence during the exploration and used FastLIO2+loop closure to obtain the pose of the LiDAR. With the extrinsics between the LiDAR and the RGB-D camera, we can obtain the corresponding camera poses. After that, we run the HOV-SG creation pipeline to generate the scene graph.

**Comment by AbbeGo** [comment]
Thank you very much for your kind and careful explanation. It is now easy to understand.
