### ISSUE TITLE
Semantic evaluation

### ISSUE THREAD

**Issue by tberriel** [hovsg/HOV-SG#13]
Hi, first of all congrats for your great work!

I wanted to ask, how did you compute the mIoU from Tables I and II of the paper?
Did you compute the metrics for each scene, and then average across all scenes? or did you aggregate classes statistics across all the scenes, and after that computed the metrics?

Also, it would be really useful if you could upload the generated scenes reconstructions. Then I would be able to compare your method against others that compute mIoU including backround objects like OpenNerf. 

Thanks!

Tomás

**Comment by abwerby** [comment]
Hello,

Regarding your first question, we computed the mean Intersection over Union (mIoU) for each scene individually and then averaged the results across all scenes. Please refer to the Experimental Evaluation section for the specific scene IDs we used for each dataset.

If you'd like to generate the scene reconstructions, including RGB images and feature maps, you can use the script application/semantic_segmentation.py. This should enable you to compare our method with others.
