### ISSUE TITLE
empty evaluate_graph.py

### ISSUE THREAD

**Issue by qugushihua** [hovsg/HOV-SG#15]
Hi,
Thank you for your great work! However, the evaluate_graph.py in the current code is empty.
![1723636676164](https://github.com/user-attachments/assets/4e0ede79-5cec-4a81-ba33-df119ad8f5e1)

I saw in the README that evaluation can be done.
![image](https://github.com/user-attachments/assets/978061c4-2200-48f7-bce0-e88d94e1c2f1)

I would like to know whether this code can be provided. Thanks!!

**Comment by Mischievous707** [comment]
I have the same problem. Looking forward to your reply. Thank!!

**Comment by martinbchnr** [comment]
We have added the routines for _hm3dsem_walks_ dataset construction as well as the hierarchical scene graph evaluation code with respect to the _hm3dsem_walks_ ground truth. Please review the updated code and let us know if you encounter any problems :)
