### ISSUE TITLE
missing semantic_segmentation_config file

### ISSUE THREAD

**Issue by yifeisu** [hovsg/HOV-SG#2]
It seems that the semanticssegmention_config file was not provided, so the segmentation task on Replica and ScanNet cannot be run?

**Comment by yifeisu** [comment]
https://github.com/hovsg/HOV-SG/blob/main/application/semantic_segmentation.py#L13
@hydra.main(version_base=None, config_path="../config", config_name="semantic_segmentation_config")
I mean the config here.

**Comment by abwerby** [comment]
I just added the semantic_segmentation_config file.
