### ISSUE TITLE
Camera Pose Incorrect Error & Building Scene Graph not Run on CUDA

### ISSUE THREAD

**Issue by EvelinYin** [hovsg/HOV-SG#3]
Hi, I use the hm3d dataset to test the scene graph following the instruction in readme. However, I got the following error when running the command `python application/create_graph.py main.dataset=hm3dsem main.dataset_path=./data/hm3dsem_walks/val/00843-DYehNKdT76V main.save_path=./data/scene_graphs/0843-DYehNKdT76V`.

![image](https://github.com/hovsg/HOV-SG/assets/42159046/ddad384f-4aa4-42db-b902-7c2543fe8d1d)

Upon checking, the extracted camera poses in folder `HOV-SG/data/hm3dsem_walks/val/00843-DYehNKdT76V/pose` by command `python data/habitat/gen_hm3dsem_from_poses.py --dataset_dir <hm3dsem_dir> --save_dir data/hm3dsem_walks/` is something like:
![image](https://github.com/hovsg/HOV-SG/assets/42159046/18a79711-f498-46cc-8646-3daeead3d85d)
which is the reason why reading it gets 7-dimensional array. I fixed this by changing the code to make the saved camera poses from the original dataset by frame to be the original 4x4 texts like (note this is not the same camera as the previous screenshot):
![image](https://github.com/hovsg/HOV-SG/assets/42159046/3baa806c-13c3-41e7-909e-a90a49d2ab2e)

However, even though this fixes the first error, I still encounter the problem that the process of merging 3d masks sequentially is extremely slow as the following:
![image](https://github.com/hovsg/HOV-SG/assets/42159046/eb1ca50f-5ff5-41ad-b778-fc7cf67fd412)

Upon checking, this process is not running on CUDA at all.
Could you provide any solution for this? Thanks.

**Comment by abwerby** [comment]
Thanks for pointing out the pose issue, I will push a fix for that soon.
regarding the speed of the merging,  what are your machine specs?

**Comment by DJC666666** [comment]
I am having the same problem, how do you change the code to make the saved camera poses from the original dataset by frame to be the original 4x4 texts?

**Comment by abwerby** [comment]
I just pushed the fix, it should work now.
