### ISSUE TITLE
RGB-D data collection in real world

### ISSUE THREAD

**Issue by YESAndy** [hovsg/HOV-SG#4]
Hi,

Thank you for sharing this great work! I notice that you use Fast-LIO for localization which is very smooth in reconstructing the real-world building. I also try to use Fast-LIO from the official repo however the performance of the localization is not that good. Could you provide details about your modified version of Fast-LIO? Thanks!!

**Comment by abwerby** [comment]
Hello, 
We used FAST_LIO_LC to create the map of the real-world building, (get the RGBD sequence to create the graph).
For the navigation tasks we used the real-world map PointCloud (FAST-LIO-LC) + Spot robot map (navigation stack) for the same building, to navigate autonomously.
Our method can work with any SLAM system as long it accurate enough + Robot with a Navigation stack.
You can take a look here:
https://github.com/yanliang-wang/FAST_LIO_LC
https://github.com/gisbi-kim/FAST_LIO_SLAM
https://github.com/HViktorTsoi/FAST_LIO_LOCALIZATION
