### ISSUE TITLE
have you tried building the scene graph online?

### ISSUE THREAD

**Issue by 18lalala** [hovsg/HOV-SG#9]
Hi,
Have you tried to build the scene graph online? I mean use a real-time odometry and RGB-D camera to provide sensor data and odometry when the robot is moving, and setup a process to take them as input to build the scene graph.

**Comment by abwerby** [comment]
This is theoretically possible, but we didn't try that. 
The merging process is a bit slow and can not run in real-time, you are also bound by how fast SAM+CLIP inference time
